# Generated by Django 4.2 on 2023-04-17 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_role_user_roleeee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='roleeee',
            new_name='role',
        ),
    ]
