# Generated by Django 4.2 on 2023-05-01 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='address_1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address_2',
        ),
    ]
